inherit_from: .rubocop_todo.yml
AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'lib/tasks/cucumber.rake'
    - 'lib/validators/*'
    - 'lib/ext/measure.rb'
Metrics/LineLength:
  Max: 130
Style/GuardClause:
  MinBodyLength: 2
Style/HashSyntax:
# Force hashes that have a symbol value to use hash rockets
  UseHashRocketsWithSymbolValues: true
