effective_date:
  year: 2013
  month: 12
  day: 31

version: 2.6.0
default_bundle: 2.6.0

calculation:
  enable_logging: false

#set to true for a "demo mode" server (large banners on header, among other things)
demo_mode: false
demo_message: "This server is for demonstration purposes; data on it will be removed every Saturday at 11:59 PM Eastern Time"

file_upload_root: "data/upload/"
